# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: 'ふぉの丼'
  site_short_description: 'ふぉのが立てたとこ'
  site_description: 'IPv6対応でなんかふぉのの自宅で動いているインスタンスです．'
  site_extended_description: ''
  site_terms: '荒らさないこと'
  site_contact_username: 'fono'
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: true
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  theme: 'system'
  trends: true
  trends_as_landing_page: true
  trendable_by_default: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
    - mod
    - moderator
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
